version: '3.7'
services:
  api:
    container_name: api
    build: api
    ports:
      - 5000:5000
  sys-stats:
    container_name: sys-stats
    build: sys-stats
    ports:
      - 3000:3000
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 80:80
    depends_on:
      - api
      - sys-stats
