apiVersion: v1
kind: Service
metadata:
  name: sys-stats-svc
spec:
  selector:
    app: sys-stats
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
    type: LoadBalancer
